[tool.black]
exclude = '\.venv/|main/migrations/'

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
ignore_missing_imports = true
strict_optional = false
